# Generated by Django 2.2.6 on 2019-10-17 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0007_auto_20191017_0358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice_area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_area', models.CharField(blank='false', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_practice_area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_practice_area', models.CharField(blank='false', max_length=200)),
                ('state', models.CharField(blank='false', max_length=200)),
                ('city', models.CharField(blank='false', max_length=200)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawyer.Lawyer')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawyer.Practice_area')),
            ],
        ),
    ]
