# Generated by Django 2.2.6 on 2019-10-17 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0009_auto_20191017_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_practice_area',
            name='state',
        ),
    ]
